[file_default]
indent_width = 4
ansi_color = false

[file.rs]
compiler = { command=["rustc", "$FilePath$", "-Z", "unstable-options", "--error-format=json"], type="rustc", optimize_option=["-O"] }
lsp = ["rls"]
formatter = ["rustfmt"]

[file.cpp]
# Respect clang-format
indent_width = 2
compiler = { command=["clang", "$FilePath$", "-o", "$FileStem$"], type="gcc", optimize_option=["-O2"] }
lsp = ["clangd"]
formatter = ["clang-format"]

[file.rb]
indent_width = 2
